spring.application.name=campusconnect

server.port=${PORT:8080}

spring.datasource.url=jdbc:h2:mem:campusconnect
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.h2.console.enabled=true